name: Clean Sweep

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  clean:
  if:${{false}} #tijdelijk uit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Remove files not in allowlist
        shell: bash
        run: |
          set -euo pipefail
          ALLOW=(
            ".github" ".github/workflows" ".github/workflows/auto-unpack-clean.yml" ".github/workflows/clean-sweep.yml"
            ".streamlit" ".streamlit/secrets.toml"
            "README.md" ".gitignore" "requirements.txt"
            "utils" "utils/shared.py" "utils/safe.py"
            "pages"
            "data" "data/materials_db.csv" "data/processes_db.csv" "data/bom_template.csv"
            "home.py"
          )
          git ls-files > all.txt
          printf "%s\n" "${ALLOW[@]}" | sed 's/[].[^$\/\\*]/\\&/g' > allow.txt
          while read -r f; do
            keep=0
            while read -r a; do
              case "$f" in "$a"|"$a"/*) keep=1; break;; esac
            done < allow.txt
            if [ $keep -eq 0 ]; then git rm -qf "$f" || true; fi
          done < all.txt

          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: clean sweep (remove clutter)"
            git push origin HEAD:main
          else
            echo "Nothing to clean"
          fi
